language: r
sudo: false
cache: packages

os:
  - linux

r_github_packages:
  - ludovikcoba/rrecsys

warnings_are_errors: true

after_success:
  - Rscript -e 'library(covr);codecov(type = "all", combine_types = TRUE)'